name: Build and Deploy Pages

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    - name: Run Build Script
      run: npm run build

    - name: Prepare Pages build
      run: |
        cp -r ./out ./out-pages

    - name: Upload Pages Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pages-dist
        path: ./out-pages

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download Pages Artifact
      uses: actions/download-artifact@v4
      with:
        name: pages-dist
        path: ./out-pages

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out-pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4